import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/Header";
import Footer from "./common/Footer";
import PopupForm from "./common/Popup";
import { ContextProvider } from "./context/MyContext";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Digital Wolf - Home",
  description: "Generated by create next app",
  metadataBase: new URL(`http://localhost:3000/`),
  alternates: {
    canonical: `./`,
  }
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Digital Wolf",
  "alternateName": "DW",
  "url": "https://www.digitalwolf.co.in/",
  "logo": "https://www.digitalwolf.co.in/assets/images/resources/logo-1.png",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+918697306015",
    "contactType": "customer service",
    "areaServed": "IN",
    "availableLanguage": "en"
  },
  "sameAs": [
    "https://www.facebook.com/digitalwolfindia/",
    "https://twitter.com/DigitalWolf12",
    "https://www.linkedin.com/company/digitalwolf1/",
    "https://www.digitalwolf.co.in/"
  ]
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
          />
            <Header/>
            {children}
            <Footer/>
            <PopupForm/>
        </ContextProvider>
      </body>
    </html>
  );
}
