

export const metadata = {
  title: "Refund Policy",
  description: "Generated by create next app",
};
export default function Layout({ children }) {
  return (
        <>
          <main>{children}</main>
        </>
  );
}